title: JC'S Typo Design
description: A website with unique typography
footer_text: Copyright 2021 Jeremy Christopher
header_feature_image: ../uploads/kristopher-roller-zepnjqycr4u-unsplash.jpg
header_text: My Dream Blog
header_text_color: "#46d8d8"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items: []
