title: JC'S World
description: "My insight "
footer_text: Copyright 2021 Jeremy Christopher
header_feature_image: ../uploads/tania-mousinho-ylpfe9ucake-unsplash.png
header_text: Welcome to JC'S World
header_text_color: "#46d8d8"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/jc-1-01.png
favicon: ../uploads/jc-1-01.png
gridlayout: true
fixednavbar: false
upzoom: true
items: []
